#!/usr/bin/env bash
#
# Fetch, verify and assemble every MiniCPM5-2B build this repository ships.
#
#   ./assemble.sh            fetch what is missing, verify, assemble
#   ./assemble.sh --check    verify what is here; download and write nothing
#
# Resumable: an asset already present and correct is skipped, and one that fails
# its checksum is deleted and re-fetched.
#
# The expected hashes below are generated by scripts/build_release.py from
# downloads that were themselves verified against the sha256 Hugging Face
# publishes. They are not hand-maintained. Re-run that script after any change
# to the release layout.
#
# DO NOT edit an expected hash to match a download. An asset that fails its
# checksum is a bad download, not a wrong hash, and relaxing the check turns a
# loud, catchable failure into a model that loads and silently produces wrong
# output.
#
set -euo pipefail

REPO="leo-kreisman/MiniCPM5-2B"
TAG="weights-v1"
BASE="https://github.com/${REPO}/releases/download/${TAG}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
PARTS="$ROOT/.parts"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

say()  { printf '\n==> %s\n' "$*"; }
note() { printf '    %s\n' "$*"; }
die()  { printf '\n[STOP] %s\n' "$*" >&2; exit 1; }

# asset-name:sha256, one per line
ASSETS_SHA="
MiniCPM5-2B-bf16.safetensors.part-0:3298f948c1767e681674c27289233fe4735a583de8872efe2a30ba534f633326
MiniCPM5-2B-bf16.safetensors.part-1:ae6ea00d91853935fa29fb54a497fa318f0ff90a9cc32165c2d2cb390d255834
MiniCPM5-2B-bf16.safetensors.part-2:e0bc8f3cd0296cd91d53c0ff274fcdc82f70e4ea99fb0f30bee6bda6dfd00cbc
MiniCPM5-2B-MLX-8bit.safetensors.part-0:3c8104c76f9fe31aa43e248459873eb14472873968a359b49fecf9b4df534b09
MiniCPM5-2B-MLX-8bit.safetensors.part-1:d35b19e09668d7c75f16516c78d2aec547d29f7f3d044531f63bf5493ed4b0c6
MiniCPM5-2B-MLX-4bit.safetensors:c207798696a4a454e7ac211b25227625466c693335941cee8904fb922f295cc1
MiniCPM5-2B-Q4_K_M.gguf:ec2d5801640099e97d8d7e8003ad4d81f336e757811f03a26173dddf386602fd
"

# target-path|sha256|asset names in concatenation order
TARGETS="
bf16/model-00000-of-00001.safetensors|14fb8e7f0a18d53d1f239773758bf581cee7e456a4523a54622c3a245b64402c|MiniCPM5-2B-bf16.safetensors.part-0 MiniCPM5-2B-bf16.safetensors.part-1 MiniCPM5-2B-bf16.safetensors.part-2
mlx-8bit/model.safetensors|82db8e423c5df99a5989f1b73dad1f44941a7800b308915f6ae7142966b32e40|MiniCPM5-2B-MLX-8bit.safetensors.part-0 MiniCPM5-2B-MLX-8bit.safetensors.part-1
mlx-4bit/model.safetensors|c207798696a4a454e7ac211b25227625466c693335941cee8904fb922f295cc1|MiniCPM5-2B-MLX-4bit.safetensors
gguf/MiniCPM5-2B-Q4_K_M.gguf|ec2d5801640099e97d8d7e8003ad4d81f336e757811f03a26173dddf386602fd|MiniCPM5-2B-Q4_K_M.gguf
"

sha_of() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d' ' -f1
  else sha256sum "$1" | cut -d' ' -f1; fi
}

fetch() {
  name="$1"; want="$2"
  dest="$PARTS/$name"
  if [ -f "$dest" ] && [ "$(sha_of "$dest")" = "$want" ]; then
    note "skip     $name"
    return 0
  fi
  if [ "$CHECK" -eq 1 ]; then
    die "$name is missing or corrupt (--check makes no changes)."
  fi
  rm -f "$dest"
  note "fetch    $name"
  curl -fL --retry 5 --retry-delay 3 -C - -o "$dest" "$BASE/$name" || die \
"download failed: $name
  A 404 here means the release asset is missing. Check:
    https://github.com/${REPO}/releases/tag/${TAG}"
  got="$(sha_of "$dest")"
  [ "$got" = "$want" ] || die "$name failed its checksum.
  expected $want
  actual   $got
  That is a bad download, not a wrong hash. Delete it and re-run; do not edit
  the expected value in this script."
  note "ok       $name"
}

say "1/3  fetching assets"
mkdir -p "$PARTS"
while IFS=: read -r n h; do
  [ -n "$n" ] || continue
  fetch "$n" "$h"
done <<< "$ASSETS_SHA"

say "2/3  assembling"
while IFS='|' read -r target h names; do
  [ -n "$target" ] || continue
  out="$ROOT/$target"
  mkdir -p "$(dirname "$out")"
  if [ -f "$out" ] && [ "$(sha_of "$out")" = "$h" ]; then
    note "skip     $target"
    continue
  fi
  if [ "$CHECK" -eq 1 ]; then
    die "$target is missing or corrupt (--check makes no changes)."
  fi
  note "assemble $target"
  : > "$out"
  for n in $names; do
    cat "$PARTS/$n" >> "$out"
  done
  got="$(sha_of "$out")"
  [ "$got" = "$h" ] || die "$target failed its checksum after assembly.
  expected $h
  actual   $got
  Every asset verified individually, so the concatenation order is wrong or an
  asset belongs to a different build. Do not serve this file."
  note "ok       $target"
done <<< "$TARGETS"

say "3/3  ready"
cat <<'EOF'

  The assembled weights are gitignored and are what SETUP.md expects to find:
    bf16/      mlx-4bit/      mlx-8bit/      gguf/

  SETUP.md section 1 for which build fits your memory; sections 2-4 for how to
  serve it. The assets under .parts/ can be deleted once assembly has verified.
EOF
